model_name: "answerdotai/ModernBERT-base"
tokenizer_name: "answerdotai/ModernBERT-base"
num_labels: 16
max_len: 128
precision: "bfloat16"
gradient_checkpointing: true

peft:
  enabled: false
  r: 8
  alpha: 16
  dropout: 0.05

loss_type: "asl"
loss_params:
  gamma_pos: 0
  gamma_neg: 4
  clip: 0.05

train_params:
  batch_size: 48
  grad_accum: 1
  epochs: 10
  lr: 0.0002
  scheduler: "cosine"
  warmup: 0.1
  weight_decay: 0.01
  seed: 123

data:
  raw_path: "data/raw/sentences.csv"
  processed_path: "data/processed/"
  split_file: "data/processed/splits.json"
  label_list_file: "data/processed/labels.json"

eval:
  metrics: ["precision", "recall", "f1", "pr_auc"]
  threshold_search: true
  pr_curves_output_dir: "plots/"

chains:
  enabled: false
  num_orders: 3

logging:
  output_dir: "runs/"
  save_every: 1
  early_stop: 3
  tensorboard: true
