model_name: "microsoft/unixcoder-base"
tokenizer_name: "microsoft/unixcoder-base"
num_labels: 16
max_len: 256
precision: "fp16"
gradient_checkpointing: false
use_single_split: true

peft:
  enabled: true
  r: 32
  alpha: 64
  dropout: 0.1

loss_type: "asl"
loss_params:
  gamma_pos: 1
  gamma_neg: 4
  clip: 0.05

use_class_weights: true
use_augmentation: false
augment_p: 0.2
use_multisample_dropout: false
use_fgm: true
label_smoothing: 0.05

train_params:
  batch_size: 8
  grad_accum: 3
  epochs: 1000
  lr: 0.0001
  scheduler: "cosine"
  warmup: 0.05
  weight_decay: 0.01
  seed: 42

data:
  raw_path: "data/raw/sentences.csv"
  processed_path: "data/processed/"
  split_file: "data/processed/splits.json"
  label_list_file: "data/processed/labels.json"

eval:
  metrics: ["precision", "recall", "f1", "roc_auc"]
  threshold_search: true

logging:
  output_dir: "runs/"
  save_every: 1
  early_stop: 7
  tensorboard: false

